[bastion]
158.160.37.48

[webservers]
10.0.1.8
10.0.2.34

[db]
10.0.1.32

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.37.48"'

[db:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.37.48"'
